# Generated by Django 2.2.1 on 2019-05-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.TextField()),
                ('endereco', models.TextField()),
                ('numero', models.DecimalField(decimal_places=5, max_digits=5)),
                ('observacao', models.TextField()),
                ('cep', models.DecimalField(decimal_places=5, max_digits=12)),
                ('bairro', models.TextField()),
                ('cidade', models.TextField()),
                ('telefone', models.DecimalField(decimal_places=5, max_digits=10)),
                ('email', models.TextField()),
            ],
        ),
    ]
