# Generated by Django 2.2.1 on 2019-05-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcbolinhas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
    ]
