# Generated by Django 2.2.1 on 2019-05-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcbolinhas', '0003_auto_20190531_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_produto', models.CharField(max_length=30)),
                ('preco_preco', models.CharField(max_length=30)),
                ('imagem', models.ImageField(blank=True, upload_to='produto_imagem')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_completo',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacao',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
