# Generated by Django 2.2.1 on 2019-05-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcbolinhas', '0004_auto_20190531_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_pedido', models.CharField(max_length=30)),
                ('descricao_pedido', models.CharField(max_length=30)),
                ('quantidade_pedido', models.BigIntegerField(default=None)),
                ('total_pedido', models.BigIntegerField(default=None)),
                ('observacao_pedido', models.CharField(max_length=30)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(upload_to='produto_image'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_preco',
            field=models.BigIntegerField(default=None),
        ),
    ]
