# Generated by Django 2.2.1 on 2019-05-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcbolinhas', '0005_auto_20190531_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='preco_preco',
            new_name='preco_produto',
        ),
    ]
