# Generated by Django 2.2.1 on 2019-05-31 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abcbolinhas', '0006_auto_20190531_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='Cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='abcbolinhas.Cliente'),
        ),
    ]
