# Generated by Django 2.2.1 on 2019-05-31 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abcbolinhas', '0007_pedidos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='produto_pedidodois',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='produto_pedidoquatro',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='produto_pedidotres',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='produto_pedidoum',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='descricao_pedido',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='produto_pedido',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
