# Generated by Django 2.2.1 on 2019-05-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abcbolinhas', '0009_auto_20190531_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='produto_pedido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='produto_pedidodois',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='produto_pedidoquatro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='produto_pedidotres',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='produto_pedidoum',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
