# Generated by Django 2.2.1 on 2019-06-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcbolinhas', '0012_auto_20190602_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='produto_pedidocinco',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='produto_pedidodois',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='produto_pedidoquatro',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='produto_pedidotres',
        ),
    ]
