# Generated by Django 2.2.1 on 2019-06-03 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abcbolinhas', '0013_auto_20190602_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='produto_pedidoum',
            new_name='produto_pedido',
        ),
    ]
